[theme]
primaryColor="#000000"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#000000F"
font="sans serif"

[server]
enableXsrfProtection = false
enableCORS = false

[client]
showSidebarNavigation = false
toolbarMode = 'minimal'
